import { useTheme } from 'next-themes'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const {theme,setTheme} = useTheme();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      {theme === "light" ? (
        <button className={styles.theme} onClick={() => setTheme('dark')}>☾</button>
      ):(
        <button className={styles.theme} onClick={() => setTheme('light')}>☀</button>
      )}
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 
          <a href="https://nextjs.org"> Camilo's portfolio</a>
        </h1>

        <p className={styles.description}>
          <code className={styles.code}>
            {'> '}Computer engineer and web developer
            </code>
        </p>
      </main>
    </div>
  )
}
